# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-26 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nieghborapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='neighborhood_image',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
