# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-26 20:51
from __future__ import unicode_literals

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('nieghborapp', '0002_auto_20181126_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='neighborhood_image',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
