# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-26 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nieghborapp', '0002_join'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='neighborhood_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='picture/'),
            preserve_default=False,
        ),
    ]
