# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-01 16:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nieghborapp', '0003_auto_20181201_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='neighborhood_image',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='neighborhood_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_neighbor', to=settings.AUTH_USER_MODEL),
        ),
    ]
